### ISSUE TITLE
Swagger JobRoles model JsonProperty missing

### ISSUE THREAD

**Issue by adammarshall745** [BlankAmber/Kainos-RRAS-API#12]
<img width="1169" alt="Screenshot 2023-12-15 at 09 19 35" src="https://github.com/BlankAmber/Kainos-RRAS-API/assets/145449058/d416538f-ae3a-4dbe-89af-e7c9de539091">

Note that once the `JsonProperty` attributes are added it still won't show up until a POST request is added.

**Comment by BlankAmber** [comment]
Fixed in #14
